### ISSUE TITLE
Autodiff for lie group jacobians reference

### ISSUE THREAD

**Issue by Edwinem** [pettni/smooth#33]
Do you have reference or explanation for how you compute the tangent space jacobians using autodiff?

[It is a cool trick that I have never seen before](https://github.com/pettni/smooth/blob/c19e35e23c8e0084314726729d0cf6729192240f/include/smooth/compat/autodiff.hpp#L94), and I can't quite wrap my head around why it works. I am guessing it has something to do with the definition of the derivative 
![image](https://user-images.githubusercontent.com/735010/165902996-115dec12-c5bf-4380-ad56-ac31ca75f14b.png)
but you are applying autodiff to only the numerator portion which I thought would be a different value.

**Comment by pettni** [comment]
Yes that's the equation I started with to arrive at the implementation. In the expanded equations below the left := is the definition of the Lie group tangent space Jacobian (from the [Micro Lie Theory](https://arxiv.org/abs/1812.01537) paper that I assume you are aware of), and the right =: is the definition of a regular Rn Jacobian since tau is a Rn tangent element. With the caveat that the limit and derivatives are component-wise, etc.

![](https://latex.codecogs.com/png.image?\dpi{110}\mathrm{d}^r&space;f_X&space;:=&space;{\text{lim}}_{\tau&space;\rightarrow&space;0}&space;\frac{f(X&space;\oplus&space;\tau)&space;\ominus&space;f(X)}{\tau}&space;=:&space;\left.&space;\frac{\mathrm{d}}{\mathrm{d}\tau}&space;\right|_{\tau&space;=&space;0}&space;f(X&space;\oplus&space;\tau)&space;\ominus&space;f(X))

**Comment by Edwinem** [comment]
Sorry maybe I am missing something.
Wouldn't this be the derivative definition of your statement.
![image](https://user-images.githubusercontent.com/735010/166191438-41e005d2-7ba3-4965-9e5a-ade5fb4f1be2.png)
don't know how to simplify it further even setting _s_ to 0.

**Comment by Edwinem** [comment]
Is this how you got to the derivative definition?
![image](https://user-images.githubusercontent.com/735010/166196838-7dd9b970-b320-4ce7-a328-8e554de47e44.png)

Else I am not quite sure then how you went from 
![image](https://user-images.githubusercontent.com/735010/166197264-2d7843a0-272e-487e-a348-f975d559b6a8.png)
to the definition you have.
![image](https://user-images.githubusercontent.com/735010/166197370-2b88f890-d1c8-4719-b082-5d03dffb9291.png)

**Comment by pettni** [comment]
You are right, I totally forgot the second term! Minor detail: the middle minus is just regular minus on Rn, and f(X) \ominus f(X) = 0.

Thanks for taking a close look! As you might have guessed this has not been peer reviewed :).

Another way to see it:

With Y = X \oplus a and dr being the right Lie group derivative the chain rule gives:

![](https://latex.codecogs.com/svg.image?\frac{\mathrm{d}}{\mathrm{d}a}&space;f(X&space;\oplus&space;a)&space;=&space;\mathrm{d}^r&space;f_Y&space;&space;\mathrm{d}^r&space;(X&space;\oplus&space;a)_a.)

Setting a = 0 makes ![](https://latex.codecogs.com/svg.image?\left.&space;\mathrm{d}^r&space;(X&space;\oplus&space;a)_a&space;\right|_{a=0}&space;=&space;I) and X = Y, so we are left with

![](https://latex.codecogs.com/svg.image?\left.&space;\frac{\mathrm{d}}{\mathrm{d}a}&space;\right|_{a&space;=&space;0}&space;f(X&space;\oplus&space;a)&space;=&space;\mathrm{d}^r&space;f_X.)

**Comment by Edwinem** [comment]
Thanks. Makes sense. Here is the fixed version for posterity.
![image](https://user-images.githubusercontent.com/735010/166587014-6274a1f0-436c-494b-bd74-a088958a1460.png)
